### ISSUE TITLE
cannot insert null value

### ISSUE THREAD

**Issue by thuantan2060** [juji/mysql-insert-multiple#1]
In your code you not check for null value (or undefined fields) so that cannot insert null value to nullable field.
To fix that I change your code to:

......................
for(var i in this.keys){
        if (obj[this.keys[i]] == undefined){
            this.query += this.valsep +'null';
        }else if( obj[this.keys[i]].string &&  obj[this.keys[i]].value)
            this.query += this.valsep + mysql.format( obj[this.keys[i]].string, obj[this.keys[i]].value );
        else this.query += this.valsep + mysql.format('?', [obj[this.keys[i]]] );
        this.valsep = ',';
    }
.......................

**Comment by juji** [comment]
use a pull request.. i can't fix this now

**Comment by juji** [comment]
Done, Thanks for raising this issue...

issue closed.
